# Generated by Django 3.2.7 on 2024-01-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_auto_20240126_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='duty',
        ),
    ]
