# Generated by Django 3.2.7 on 2024-01-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='available_dates',
        ),
    ]
