# Generated by Django 3.2.7 on 2024-01-26 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_remove_reservation_available_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='number_of_guests',
            field=models.PositiveIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, default='N/A', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
