# Generated by Django 3.2.7 on 2024-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_auto_20240126_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
