# Generated by Django 3.2.7 on 2024-01-26 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_remove_reservation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='special_request',
        ),
    ]
