# Generated by Django 3.2.7 on 2024-01-26 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0011_auto_20240126_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
