# Generated by Django 3.2.7 on 2024-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0013_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
