# Generated by Django 3.2.7 on 2024-01-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0019_alter_reservation_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='phone_number',
        ),
    ]
