# Generated by Django 3.2.7 on 2024-01-26 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0021_reservation_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='number_of_guests',
            field=models.PositiveIntegerField(default='1', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
