# Generated by Django 3.2.7 on 2024-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0022_reservation_number_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
