# Generated by Django 3.2.7 on 2024-01-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0023_reservation_special_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
