# Generated by Django 3.2.7 on 2024-01-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0026_auto_20240126_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='comment',
            new_name='comments',
        ),
    ]
