# Generated by Django 3.2.7 on 2024-01-27 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('details', '0027_rename_comment_feedback_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.category')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_field1', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_field2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dessert',
                'verbose_name_plural': 'Desserts',
            },
        ),
        migrations.CreateModel(
            name='MainDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_field1', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_field2', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Main Dish',
                'verbose_name_plural': 'Main Dishes',
            },
        ),
        migrations.RemoveField(
            model_name='dailyduty',
            name='employee',
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='DailyDuty',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
